import { DefaultTheme } from "styled-components";

export const darkTheme: DefaultTheme = {
  navbarBackground: "var(--primaryBackgroundColorDark)",
  bodyBackground: "var(--secondaryBackgroundColorDark)",
  navColor: "var(--white)",
  titleColor: "var(--primaryColorDark)",
  textColor: "var(--primaryColorDark)",
  linearRightColor: "var(--linearRightColorDark)",
  linearLeftColor: "var(--linearLeftColorDark)",
  balackAndWhite: "var(--white)",
  modalBackground: "var(--modalDarkBackground)",
  modalShadow: "var(--modalDarkShadow)",
  modalCloseStroke: "var(--modalCloseStrokeDark)",
  labelColor: "var(--labelColor)",
  inputBackground: "var(--inputDarkBackground)",
  buttonBackground: "var(--buttonBackgroundDark)",
  emailBackground: "var(--emailDarkBackground)",
  emailBorder: "var(--emailDarkBorder)",
  selectBackground: "var(--selectDarkBackground)",
  starsColor: "var(--starsDarkColor)",
  cardBackground: "var(--cardDarkBackground)",
  iconsColorAndButtonBorder: "var(--iconsDarkColorAndButtonBorder)",
  figmaBg: "var(--figmaDarkBg)",
  firstBoxShadow: "var(--firstBoxShadowDark)",
  secondBoxShadow: "var(--secondBoxShadowDark)",
  tooltipFirstShdow: "var(--tooltipFirstShdowDark)",
  tooltipSecondShdow: "var(--tooltipSecondShdowDark)",
  errorColor: "var(--errorColorDark)",
  errorNumberColor: "var(--errorNumberColorDark)",
};
